# A unit the splitter must decline: split nothing, say why, compile whole, be right.
foreach(required SPLITTER SOURCE WORKDIR CXX EXPECT_MESSAGE EXPECT_OUTPUT)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} must be defined")
  endif()
endforeach()
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env CPP_SPLITTER_VERBOSE=1
          "${SPLITTER}" "${SOURCE}" "${WORKDIR}/split" --compile -o "${WORKDIR}/program" --cxx "${CXX}"
  OUTPUT_VARIABLE o ERROR_VARIABLE e RESULT_VARIABLE rc)
set(log "${o}${e}")
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "cpp-splitter failed (${rc}):\n${log}")
endif()
if(NOT log MATCHES "not splitting")
  message(FATAL_ERROR "the unit was not declined:\n${log}")
endif()
if(NOT log MATCHES "${EXPECT_MESSAGE}")
  message(FATAL_ERROR "declined for another reason than '${EXPECT_MESSAGE}':\n${log}")
endif()
if(log MATCHES "falling back")
  message(FATAL_ERROR "a decline must come before any piece is written, not as a fallback:\n${log}")
endif()
execute_process(COMMAND "${WORKDIR}/program" OUTPUT_VARIABLE out RESULT_VARIABLE prc)
string(STRIP "${out}" out)
if(NOT prc EQUAL 0 OR NOT out STREQUAL "${EXPECT_OUTPUT}")
  message(FATAL_ERROR "program wrong: rc=${prc} out='${out}' expected '${EXPECT_OUTPUT}'")
endif()
message(STATUS "ok: declined for the stated reason, compiled whole, and right")
