# The launcher on one unit with extra compiler flags (FLAGS, a ;-list), linked with those and
# LDFLAGS, and run.
foreach(required SPLITTER SOURCE WORKDIR CXX FLAGS EXPECT)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} must be defined")
  endif()
endforeach()
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}")
set(object "${WORKDIR}/unit.o")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env CPP_SPLITTER_VERBOSE=1
          "${SPLITTER}" "${CXX}" ${FLAGS} -c -o "${object}" "${SOURCE}"
  OUTPUT_VARIABLE o ERROR_VARIABLE e RESULT_VARIABLE rc)
set(log "${o}${e}")
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "launcher failed (${rc}):\n${log}")
endif()
if(log MATCHES "fallback|falling back|not splitting")
  message(FATAL_ERROR "the unit was not split:\n${log}")
endif()
if(log MATCHES "Parse error")
  message(FATAL_ERROR "the parse reported errors on a unit the compiler accepts:\n${log}")
endif()
execute_process(COMMAND "${CXX}" ${FLAGS} ${LDFLAGS} -o "${WORKDIR}/program" "${object}"
                RESULT_VARIABLE lrc OUTPUT_VARIABLE lo ERROR_VARIABLE le)
if(NOT lrc EQUAL 0)
  message(FATAL_ERROR "link failed:\n${lo}${le}")
endif()
execute_process(COMMAND "${WORKDIR}/program" OUTPUT_VARIABLE out RESULT_VARIABLE prc)
string(STRIP "${out}" out)
if(NOT prc EQUAL 0 OR NOT out STREQUAL "${EXPECT}")
  message(FATAL_ERROR "program wrong: rc=${prc} out='${out}' expected '${EXPECT}'")
endif()
message(STATUS "ok: split under '${FLAGS}' and the program prints ${EXPECT}")
