# Two units include two.h and emit f_of() and g_of(): the store holds one object each. An
# edit to f_of()'s body is one new object -- g_of()'s untouched, no per-unit compile -- and
# an edit to both is two. The shared piece is the store's copy of the header plus one body,
# keyed on that text, so a body edit reaches its own key and no other. TODO/51.
foreach(required SPLITTER SOURCE_DIR WORKDIR CXX)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} must be defined")
  endif()
endforeach()
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}/src" "${WORKDIR}/store")
foreach(f two.h a.cpp b.cpp main.cpp)
  configure_file("${SOURCE_DIR}/${f}" "${WORKDIR}/src/${f}" COPYONLY)
endforeach()

function(compile unit label)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env CPP_SPLITTER_VERBOSE=1 "CPP_SPLITTER_STORE=${WORKDIR}/store"
            "${SPLITTER}" "${CXX}" -std=c++17 -MD -MF "${WORKDIR}/${unit}.d" -MT "${WORKDIR}/${unit}.o"
            -c -o "${WORKDIR}/${unit}.o" "${WORKDIR}/src/${unit}.cpp"
    OUTPUT_VARIABLE o ERROR_VARIABLE e RESULT_VARIABLE rc)
  set(log "${o}${e}")
  file(WRITE "${WORKDIR}/${unit}-${label}.log" "${log}")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "${label}: launcher failed on ${unit}.cpp (${rc}):\n${log}")
  endif()
  if(log MATCHES "fallback|falling back|not splitting")
    message(FATAL_ERROR "${label}: ${unit}.cpp was not split:\n${log}")
  endif()
  if(log MATCHES "compiling [0-9]+ header dep")
    message(FATAL_ERROR "${label}: ${unit}.cpp compiled a per-unit header piece; every piece here is shareable:\n${log}")
  endif()
  set(${unit}_log "${log}" PARENT_SCOPE)
endfunction()
function(build_and_check expect label)
  compile(a "${label}")
  compile(b "${label}")
  compile(main "${label}")
  execute_process(COMMAND "${CXX}" -o "${WORKDIR}/program" "${WORKDIR}/a.o" "${WORKDIR}/b.o" "${WORKDIR}/main.o"
                  RESULT_VARIABLE lrc OUTPUT_VARIABLE lo ERROR_VARIABLE le)
  if(NOT lrc EQUAL 0)
    message(FATAL_ERROR "${label}: link failed:\n${lo}${le}")
  endif()
  execute_process(COMMAND "${WORKDIR}/program" OUTPUT_VARIABLE out RESULT_VARIABLE prc)
  string(STRIP "${out}" out)
  if(NOT prc EQUAL 0 OR NOT out STREQUAL "${expect}")
    message(FATAL_ERROR "${label}: program wrong: rc=${prc} out='${out}' expected '${expect}'")
  endif()
  set(a_log "${a_log}" PARENT_SCOPE)
  set(b_log "${b_log}" PARENT_SCOPE)
endfunction()
function(store_key twin out_var)
  file(GLOB twins "${twin}")
  list(LENGTH twins n)
  if(NOT n EQUAL 1)
    message(FATAL_ERROR "expected one piece at ${twin}, found ${n}")
  endif()
  file(STRINGS "${twins}" store_line REGEX "^// Store: ")
  if(NOT store_line)
    message(FATAL_ERROR "${twins} is not a shared piece")
  endif()
  string(REGEX REPLACE "^// Store: " "" key "${store_line}")
  set(${out_var} "${key}" PARENT_SCOPE)
endfunction()
function(object_of key out_var)
  file(GLOB objs "${WORKDIR}/store/${key}-*.o")
  list(LENGTH objs n)
  if(NOT n EQUAL 1)
    message(FATAL_ERROR "the store holds ${n} object(s) for key ${key}, expected 1")
  endif()
  set(${out_var} "${objs}" PARENT_SCOPE)
endfunction()
function(count_objects out_var)
  file(GLOB objs "${WORKDIR}/store/*.o")
  list(LENGTH objs n)
  set(${out_var} "${n}" PARENT_SCOPE)
endfunction()
function(edit from to)
  file(READ "${WORKDIR}/src/two.h" text)
  string(REPLACE "${from}" "${to}" text "${text}")
  file(WRITE "${WORKDIR}/src/two.h" "${text}")
endfunction()

# Cold: one object per function.
build_and_check("48 252" cold)
store_key("${WORKDIR}/a.o.split/include/two.h_*_f_of.cpp" f_key)
store_key("${WORKDIR}/a.o.split/include/two.h_*_g_of.cpp" g_key)
object_of("${f_key}" f_obj)
object_of("${g_key}" g_obj)
count_objects(n0)
if(NOT n0 EQUAL 2)
  message(FATAL_ERROR "cold: the store holds ${n0} objects, expected 2")
endif()
if(NOT b_log MATCHES "shared pieces: 2 of 2")
  message(FATAL_ERROR "cold: b.cpp did not link both shared pieces:\n${b_log}")
endif()

# Edit f_of(): one new key, one new object; g_of()'s key and object untouched.
file(TIMESTAMP "${g_obj}" g_before "%s")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
edit("return v * 3;" "return v * 30;")
build_and_check("102 2520" edit-f)
store_key("${WORKDIR}/a.o.split/include/two.h_*_f_of.cpp" f_key2)
store_key("${WORKDIR}/a.o.split/include/two.h_*_g_of.cpp" g_key2)
if(f_key2 STREQUAL f_key)
  message(FATAL_ERROR "edit-f: f_of()'s key did not change")
endif()
if(NOT g_key2 STREQUAL g_key)
  message(FATAL_ERROR "edit-f: g_of()'s key changed on an edit to f_of()")
endif()
object_of("${f_key2}" f_obj2)
file(TIMESTAMP "${g_obj}" g_after "%s")
if(NOT g_after STREQUAL g_before)
  message(FATAL_ERROR "edit-f: g_of()'s object was rewritten on an edit to f_of()")
endif()
count_objects(n1)
if(NOT n1 EQUAL 3)
  message(FATAL_ERROR "edit-f: the store holds ${n1} objects, expected 3 (f old, f new, g)")
endif()
if(NOT a_log MATCHES "compiling 1 shared piece")
  message(FATAL_ERROR "edit-f: a.cpp did not compile exactly one shared piece:\n${a_log}")
endif()
if(b_log MATCHES "compiling [0-9]+ shared piece")
  message(FATAL_ERROR "edit-f: b.cpp compiled a shared piece a.cpp had built:\n${b_log}")
endif()

# Edit both: two new keys, two compiles.
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
edit("return v * 30;" "return v * 300;")
edit("return v + 40;" "return v + 400;")
build_and_check("1002 241200" edit-both)
count_objects(n2)
if(NOT n2 EQUAL 5)
  message(FATAL_ERROR "edit-both: the store holds ${n2} objects, expected 5")
endif()
if(NOT a_log MATCHES "compiling 2 shared piece")
  message(FATAL_ERROR "edit-both: a.cpp did not compile exactly two shared pieces:\n${a_log}")
endif()
message(STATUS "one body edited: one shared compile; two: two; the other object untouched")
