# Two units include shared.h and emit shared_fn(): the store holds one object for it, the
# second unit links it without compiling, and an edit to the body is compiled once. A header
# that only compiles in its includer's context (needs_ctx.h) is split through the per-unit
# piece: its shared compile fails once, is marked, and is not retried. TODO/51.
foreach(required SPLITTER SOURCE_DIR WORKDIR CXX)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} must be defined")
  endif()
endforeach()
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}/src" "${WORKDIR}/store")
foreach(f shared.h needs_ctx.h a.cpp b.cpp main.cpp)
  configure_file("${SOURCE_DIR}/${f}" "${WORKDIR}/src/${f}" COPYONLY)
endforeach()

function(compile unit label)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env CPP_SPLITTER_VERBOSE=1 "CPP_SPLITTER_STORE=${WORKDIR}/store"
            "${SPLITTER}" "${CXX}" -std=c++17 -MD -MF "${WORKDIR}/${unit}.d" -MT "${WORKDIR}/${unit}.o"
            -c -o "${WORKDIR}/${unit}.o" "${WORKDIR}/src/${unit}.cpp"
    OUTPUT_VARIABLE o ERROR_VARIABLE e RESULT_VARIABLE rc)
  set(log "${o}${e}")
  file(WRITE "${WORKDIR}/${unit}-${label}.log" "${log}")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "${label}: launcher failed on ${unit}.cpp (${rc}):\n${log}")
  endif()
  if(log MATCHES "fallback|falling back|not splitting")
    message(FATAL_ERROR "${label}: ${unit}.cpp was not split:\n${log}")
  endif()
  set(${unit}_log "${log}" PARENT_SCOPE)
endfunction()

function(link_and_check expect label)
  execute_process(COMMAND "${CXX}" -o "${WORKDIR}/program" "${WORKDIR}/a.o" "${WORKDIR}/b.o" "${WORKDIR}/main.o"
                  RESULT_VARIABLE lrc OUTPUT_VARIABLE lo ERROR_VARIABLE le)
  if(NOT lrc EQUAL 0)
    message(FATAL_ERROR "${label}: link failed:\n${lo}${le}")
  endif()
  execute_process(COMMAND "${WORKDIR}/program" OUTPUT_VARIABLE out RESULT_VARIABLE prc)
  string(STRIP "${out}" out)
  if(NOT prc EQUAL 0 OR NOT out STREQUAL "${expect}")
    message(FATAL_ERROR "${label}: program wrong: rc=${prc} out='${out}' expected '${expect}'")
  endif()
endfunction()

function(store_key twin out_var)
  file(GLOB twins "${twin}")
  list(LENGTH twins n)
  if(NOT n EQUAL 1)
    message(FATAL_ERROR "expected one piece at ${twin}, found ${n}")
  endif()
  file(STRINGS "${twins}" store_line REGEX "^// Store: ")
  if(NOT store_line)
    message(FATAL_ERROR "${twins} is not a shared piece")
  endif()
  string(REGEX REPLACE "^// Store: " "" key "${store_line}")
  set(${out_var} "${key}" PARENT_SCOPE)
endfunction()

compile(a first)
compile(b first)
compile(main first)
link_and_check("27 13" first)

store_key("${WORKDIR}/a.o.split/include/shared.h_*_shared_fn.cpp" a_key)
store_key("${WORKDIR}/b.o.split/include/shared.h_*_shared_fn.cpp" b_key)
if(NOT a_key STREQUAL b_key)
  message(FATAL_ERROR "the two units' pieces for shared_fn() have different store keys: ${a_key} ${b_key}")
endif()
file(GLOB shared_objs "${WORKDIR}/store/${a_key}-*.o")
list(LENGTH shared_objs n_shared)
if(NOT n_shared EQUAL 1)
  message(FATAL_ERROR "the store holds ${n_shared} object(s) for shared_fn(): '${shared_objs}'")
endif()
if(NOT a_log MATCHES "\\$ [^\n]*${a_key}\\.cpp")
  message(FATAL_ERROR "a.cpp did not compile the shared piece for shared_fn():\n${a_log}")
endif()
if(b_log MATCHES "\\$ [^\n]*${b_key}\\.cpp")
  message(FATAL_ERROR "b.cpp compiled the shared piece for shared_fn() that a.cpp had built:\n${b_log}")
endif()
if(NOT b_log MATCHES "shared piece \\.o: [^\n]*${b_key}")
  message(FATAL_ERROR "b.cpp did not link the shared piece for shared_fn():\n${b_log}")
endif()

# needs_ctx.h: the shared compile failed once, the unit compiled its own piece.
store_key("${WORKDIR}/a.o.split/include/needs_ctx.h_*_ctx_fn.cpp" ctx_key)
file(GLOB ctx_fail "${WORKDIR}/store/${ctx_key}-*.o.fail")
if(NOT ctx_fail)
  message(FATAL_ERROR "no failure marker for ctx_fn()'s shared piece in the store")
endif()
if(NOT a_log MATCHES "shared piece failed, the unit compiles its own")
  message(FATAL_ERROR "a.cpp did not report the failed shared compile of ctx_fn():\n${a_log}")
endif()
file(GLOB ctx_twin_obj "${WORKDIR}/a.o.split/include/needs_ctx.h_*_ctx_fn.o")
if(NOT ctx_twin_obj)
  message(FATAL_ERROR "a.cpp did not compile its own piece for ctx_fn()")
endif()

# Edit shared_fn()'s body: one shared compile, by whichever unit comes first.
file(TIMESTAMP "${shared_objs}" obj_before "%s")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
file(READ "${WORKDIR}/src/shared.h" text)
string(REPLACE "return v * 7;" "return v * 70;" text "${text}")
file(WRITE "${WORKDIR}/src/shared.h" "${text}")
compile(a edit)
compile(b edit)
compile(main edit)
link_and_check("153 139" edit)
file(TIMESTAMP "${shared_objs}" obj_after "%s")
if(obj_after STREQUAL obj_before)
  message(FATAL_ERROR "the shared piece for shared_fn() was not recompiled after the edit")
endif()
if(NOT a_log MATCHES "\\$ [^\n]*${a_key}\\.cpp")
  message(FATAL_ERROR "a.cpp did not recompile the shared piece after the edit:\n${a_log}")
endif()
if(b_log MATCHES "\\$ [^\n]*${b_key}\\.cpp" OR b_log MATCHES "compiling [0-9]+ header dep")
  message(FATAL_ERROR "b.cpp compiled again what a.cpp had rebuilt:\n${b_log}")
endif()
if(a_log MATCHES "\\$ [^\n]*${ctx_key}\\.cpp")
  message(FATAL_ERROR "a.cpp retried ctx_fn()'s shared compile, which is marked failed:\n${a_log}")
endif()
# The piece's text is reproducible from the twin alone: a split produced on the cluster
# leaves its store there, and the launcher writes the piece again with the same key.
file(REMOVE "${WORKDIR}/store/${a_key}.cpp")
compile(b regen)
if(NOT EXISTS "${WORKDIR}/store/${a_key}.cpp")
  message(FATAL_ERROR "b.cpp did not write the shared piece for shared_fn() back to the store")
endif()
if(b_log MATCHES "\\$ [^\n]*${b_key}\\.cpp")
  message(FATAL_ERROR "b.cpp recompiled the shared piece after its source was rewritten from the twin:\n${b_log}")
endif()
message(STATUS "ok: one shared object for shared_fn(), reused by b.cpp and rebuilt once on edit; ctx_fn() split per unit")
