# Three units through the launcher: a.cpp calls alpha(), b.cpp calls beta(), both from ops.h.
# After an edit to alpha()'s body, b.cpp's copy of ops.h must be byte-identical, its object
# untouched, and the program must print alpha's new result. TODO/48.
# gamma() is named by a template in ops.h and called through it by main.cpp: every copy
# declares it and a piece defines it; an edit to its body recompiles that one piece in
# b.cpp, no PCH and nothing else. TODO/49.
foreach(required SPLITTER SOURCE_DIR WORKDIR CXX)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} must be defined")
  endif()
endforeach()
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}/src")
foreach(f ops.h a.cpp b.cpp main.cpp)
  configure_file("${SOURCE_DIR}/${f}" "${WORKDIR}/src/${f}" COPYONLY)
endforeach()

function(compile unit label)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env CPP_SPLITTER_VERBOSE=1
            "${SPLITTER}" "${CXX}" -std=c++17 -MD -MF "${WORKDIR}/${unit}.d" -MT "${WORKDIR}/${unit}.o"
            -c -o "${WORKDIR}/${unit}.o" "${WORKDIR}/src/${unit}.cpp"
    OUTPUT_VARIABLE o ERROR_VARIABLE e RESULT_VARIABLE rc)
  set(log "${o}${e}")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "${label}: launcher failed on ${unit}.cpp (${rc}):\n${log}")
  endif()
  if(log MATCHES "fallback|falling back|not splitting")
    message(FATAL_ERROR "${label}: ${unit}.cpp was not split:\n${log}")
  endif()
  set(${unit}_log "${log}" PARENT_SCOPE)
endfunction()

function(link_and_check expect label)
  execute_process(COMMAND "${CXX}" -o "${WORKDIR}/program" "${WORKDIR}/a.o" "${WORKDIR}/b.o" "${WORKDIR}/main.o"
                  RESULT_VARIABLE lrc OUTPUT_VARIABLE lo ERROR_VARIABLE le)
  if(NOT lrc EQUAL 0)
    message(FATAL_ERROR "${label}: link failed:\n${lo}${le}")
  endif()
  execute_process(COMMAND "${WORKDIR}/program" OUTPUT_VARIABLE out RESULT_VARIABLE prc)
  string(STRIP "${out}" out)
  if(NOT prc EQUAL 0 OR NOT out STREQUAL "${expect}")
    message(FATAL_ERROR "${label}: program wrong: rc=${prc} out='${out}' expected '${expect}'")
  endif()
endfunction()

compile(a first)
compile(b first)
compile(main first)
link_and_check("60 3 1" first)

set(b_copy "${WORKDIR}/b.o.split/include/ops.h")
if(NOT EXISTS "${b_copy}")
  message(FATAL_ERROR "no copy of ops.h for b.cpp at ${b_copy}")
endif()
file(READ "${b_copy}" b_copy_before)
if(b_copy_before MATCHES "return v \\* 10")
  message(FATAL_ERROR "b.cpp's copy of ops.h defines alpha(), which b.cpp does not emit:\n${b_copy_before}")
endif()
if(NOT b_copy_before MATCHES "int alpha\\(int v\\);")
  message(FATAL_ERROR "b.cpp's copy of ops.h does not declare alpha():\n${b_copy_before}")
endif()
if(b_copy_before MATCHES "return v - 1")
  message(FATAL_ERROR "b.cpp's copy of ops.h defines gamma(), which a template names and b.cpp does not emit:\n${b_copy_before}")
endif()
if(NOT b_copy_before MATCHES "int gamma\\(int v\\);")
  message(FATAL_ERROR "b.cpp's copy of ops.h does not declare gamma():\n${b_copy_before}")
endif()
if(NOT b_copy_before MATCHES "return needs_definition\\(v\\);")
  message(FATAL_ERROR "b.cpp's copy of ops.h does not keep delta()'s body, which needs a definition the unit lacks:\n${b_copy_before}")
endif()
file(GLOB b_delta_piece "${WORKDIR}/b.o.split/include/ops.h_*_delta.o")
if(b_delta_piece)
  message(FATAL_ERROR "b.cpp has a piece for delta(), whose body needs a definition the unit lacks: '${b_delta_piece}'")
endif()
file(GLOB b_gamma_piece "${WORKDIR}/b.o.split/include/ops.h_*_gamma.o")
list(LENGTH b_gamma_piece n_gamma)
if(NOT n_gamma EQUAL 1)
  message(FATAL_ERROR "b.cpp has no piece for gamma() under b.o.split/include: '${b_gamma_piece}'")
endif()
# The pieces' objects, not b.o itself: the launcher touches an object it leaves as it is,
# so that the build system does not rebuild it every time.
file(GLOB b_pieces "${WORKDIR}/b.o.split/*.o" "${WORKDIR}/b.o.split/include/*.o")
set(b_obj_before "")
foreach(o ${b_pieces})
  file(TIMESTAMP "${o}" t "%s")
  string(APPEND b_obj_before "${o}=${t};")
endforeach()

# Edit alpha()'s body.
file(READ "${WORKDIR}/src/ops.h" ops)
string(REPLACE "return v * 10;" "return v * 100;" ops "${ops}")
file(WRITE "${WORKDIR}/src/ops.h" "${ops}")

compile(a edit)
compile(b edit)
compile(main edit)
link_and_check("600 3 1" edit)

file(READ "${b_copy}" b_copy_after)
if(NOT b_copy_after STREQUAL b_copy_before)
  message(FATAL_ERROR "b.cpp's copy of ops.h changed under an edit to a body b.cpp does not emit")
endif()
set(b_obj_after "")
foreach(o ${b_pieces})
  file(TIMESTAMP "${o}" t "%s")
  string(APPEND b_obj_after "${o}=${t};")
endforeach()
if(NOT b_obj_after STREQUAL b_obj_before OR b_log MATCHES "compile \\(seq\\)|compiling [0-9]+ split")
  message(FATAL_ERROR "b.cpp's pieces were recompiled for an edit to a body it does not emit:\n${b_log}")
endif()
if(NOT b_log MATCHES "re-sliced nothing")
  message(FATAL_ERROR "b.cpp did not take the declared-only path:\n${b_log}")
endif()
# Edit gamma()'s body: one piece recompiles in b.cpp, no PCH, nothing else.
set(b_others "")
foreach(o ${b_pieces})
  if(NOT o STREQUAL b_gamma_piece)
    file(TIMESTAMP "${o}" t "%s")
    string(APPEND b_others "${o}=${t};")
  endif()
endforeach()
file(TIMESTAMP "${b_gamma_piece}" gamma_before "%s")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
file(READ "${WORKDIR}/src/ops.h" ops)
string(REPLACE "return v - 1;" "return v - 10;" ops "${ops}")
file(WRITE "${WORKDIR}/src/ops.h" "${ops}")

compile(a gamma)
compile(b gamma)
compile(main gamma)
link_and_check("600 3 -8" gamma)

if(b_log MATCHES "Building PCH")
  message(FATAL_ERROR "b.cpp rebuilt its PCH for an edit to gamma()'s body:\n${b_log}")
endif()
if(NOT b_log MATCHES "re-sliced its piece")
  message(FATAL_ERROR "b.cpp did not re-slice gamma()'s piece:\n${b_log}")
endif()
file(TIMESTAMP "${b_gamma_piece}" gamma_after "%s")
if(gamma_after STREQUAL gamma_before)
  message(FATAL_ERROR "b.cpp's piece for gamma() was not recompiled after the edit:\n${b_log}")
endif()
set(b_others_after "")
foreach(o ${b_pieces})
  if(NOT o STREQUAL b_gamma_piece)
    file(TIMESTAMP "${o}" t "%s")
    string(APPEND b_others_after "${o}=${t};")
  endif()
endforeach()
if(NOT b_others_after STREQUAL b_others)
  message(FATAL_ERROR "b.cpp recompiled pieces other than gamma()'s for an edit to gamma()'s body:\n${b_log}")
endif()
message(STATUS "ok: b.cpp's copy and object are untouched by the alpha edit; the gamma edit recompiles one piece")
