# heavy.h: a body that is long to compile beside one that is not. Cold, both are shared
# pieces compiled once. An edit to light() then compiles light()'s piece alone: heavy()'s
# object keeps its timestamp, and light()'s piece never parsed heavy()'s body -- the store's
# copy of the header declares it. TODO/51.
foreach(required SPLITTER SOURCE_DIR WORKDIR CXX)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} must be defined")
  endif()
endforeach()
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}/src" "${WORKDIR}/store")
foreach(f heavy.h a.cpp b.cpp main.cpp)
  configure_file("${SOURCE_DIR}/${f}" "${WORKDIR}/src/${f}" COPYONLY)
endforeach()

function(compile unit label)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env CPP_SPLITTER_VERBOSE=1 "CPP_SPLITTER_STORE=${WORKDIR}/store"
            "${SPLITTER}" "${CXX}" -std=c++17 -MD -MF "${WORKDIR}/${unit}.d" -MT "${WORKDIR}/${unit}.o"
            -c -o "${WORKDIR}/${unit}.o" "${WORKDIR}/src/${unit}.cpp"
    OUTPUT_VARIABLE o ERROR_VARIABLE e RESULT_VARIABLE rc)
  set(log "${o}${e}")
  file(WRITE "${WORKDIR}/${unit}-${label}.log" "${log}")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "${label}: launcher failed on ${unit}.cpp (${rc}):\n${log}")
  endif()
  if(log MATCHES "fallback|falling back|not splitting|compiling [0-9]+ header dep")
    message(FATAL_ERROR "${label}: ${unit}.cpp was not split through the store:\n${log}")
  endif()
  set(${unit}_log "${log}" PARENT_SCOPE)
endfunction()
function(build_and_check expect label)
  compile(a "${label}")
  compile(b "${label}")
  compile(main "${label}")
  execute_process(COMMAND "${CXX}" -o "${WORKDIR}/program" "${WORKDIR}/a.o" "${WORKDIR}/b.o" "${WORKDIR}/main.o"
                  RESULT_VARIABLE lrc OUTPUT_VARIABLE lo ERROR_VARIABLE le)
  if(NOT lrc EQUAL 0)
    message(FATAL_ERROR "${label}: link failed:\n${lo}${le}")
  endif()
  execute_process(COMMAND "${WORKDIR}/program" OUTPUT_VARIABLE out RESULT_VARIABLE prc)
  string(STRIP "${out}" out)
  if(NOT prc EQUAL 0 OR NOT out STREQUAL "${expect}")
    message(FATAL_ERROR "${label}: program wrong: rc=${prc} out='${out}' expected '${expect}'")
  endif()
  set(a_log "${a_log}" PARENT_SCOPE)
endfunction()
function(store_key twin out_var)
  file(GLOB twins "${twin}")
  list(LENGTH twins n)
  if(NOT n EQUAL 1)
    message(FATAL_ERROR "expected one piece at ${twin}, found ${n}")
  endif()
  file(STRINGS "${twins}" store_line REGEX "^// Store: ")
  if(NOT store_line)
    message(FATAL_ERROR "${twins} is not a shared piece")
  endif()
  string(REGEX REPLACE "^// Store: " "" key "${store_line}")
  set(${out_var} "${key}" PARENT_SCOPE)
endfunction()

build_and_check("5 -1" cold)
store_key("${WORKDIR}/a.o.split/include/heavy.h_*_heavy.cpp" heavy_key)
store_key("${WORKDIR}/a.o.split/include/heavy.h_*_light.cpp" light_key)
file(GLOB heavy_obj "${WORKDIR}/store/${heavy_key}-*.o")
if(NOT heavy_obj)
  message(FATAL_ERROR "cold: no shared object for heavy()")
endif()
# light()'s shared piece sees heavy() as a declaration: the store's copy of the header.
file(STRINGS "${WORKDIR}/store/${light_key}.cpp" include_line REGEX "^#include \"")
string(REGEX REPLACE "^#include \"(.*)\"$" "\\1" copy "${include_line}")
file(READ "${copy}" copy_text)
if(copy_text MATCHES "sum_block<7000>")
  message(FATAL_ERROR "the store's copy of heavy.h still carries heavy()'s body:\n${copy_text}")
endif()
if(NOT copy_text MATCHES "long heavy\\(int v\\);")
  message(FATAL_ERROR "the store's copy of heavy.h does not declare heavy():\n${copy_text}")
endif()

file(TIMESTAMP "${heavy_obj}" heavy_before "%s")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
file(READ "${WORKDIR}/src/heavy.h" text)
string(REPLACE "return v + 1; }" "return v + 10; }" text "${text}")
file(WRITE "${WORKDIR}/src/heavy.h" "${text}")
build_and_check("14 -10" edit-light)
file(TIMESTAMP "${heavy_obj}" heavy_after "%s")
if(NOT heavy_after STREQUAL heavy_before)
  message(FATAL_ERROR "edit-light: heavy()'s object was recompiled on an edit to light()")
endif()
if(NOT a_log MATCHES "compiling 1 shared piece")
  message(FATAL_ERROR "edit-light: expected exactly one shared compile:\n${a_log}")
endif()
message(STATUS "light() edited: one shared compile, heavy()'s object untouched, its body never parsed by light()'s piece")
