#!/usr/bin/env python3
"""The module benchmark project, written out: one interface unit with 40 exported non-inline
functions and 4 inline ones, 30 importers that each use a handful of them, and a main.

Committed as generated, so that the benchmark's body edit patches a file the build system
watches; rerun this only to change the shape. TODO/43 Phase 3."""
import os, textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
N_FUNCS, N_INLINE, N_USERS = 40, 4, 30

def body(i):
    # Enough work per body that a compile is not just the headers: a loop over a vector, a
    # string, and a std::map lookup, all through the global module fragment's headers.
    return textwrap.dedent(f"""\
        export int compute_{i}(int n) {{
            std::vector<int> v(static_cast<std::size_t>(n % 97 + 3), {i});
            std::map<std::string, int> m;
            for (std::size_t k = 0; k < v.size(); ++k) m[std::to_string(k * {i + 1})] += static_cast<int>(k);
            long acc = 0;
            for (const auto& [key, value] : m) acc += static_cast<long>(key.size()) * value;
            std::sort(v.begin(), v.end());
            return static_cast<int>(acc % 1000) + v.front() + n;
        }}
        """)

iface = ["// Generated by generate.py: the interface unit the benchmark edits.",
         "module;", "#include <vector>", "#include <string>", "#include <map>", "#include <algorithm>",
         "#include <cstddef>", "export module mathlib;", ""]
for i in range(N_INLINE):
    iface.append(f"export inline int fast_{i}(int v) {{ return v * {i + 2} + 1; }}")
iface.append("")
for i in range(N_FUNCS):
    iface.append(body(i))
open(os.path.join(HERE, "mathlib.cppm"), "w").write("\n".join(iface))

for u in range(N_USERS):
    funcs = [(u * 7 + k * 3) % N_FUNCS for k in range(5)]
    calls = " + ".join(f"compute_{f}(n + {k})" for k, f in enumerate(funcs))
    src = textwrap.dedent(f"""\
        // Generated by generate.py: importer {u}.
        import mathlib;
        #include <vector>
        #include <string>
        #include <algorithm>
        #include <numeric>

        static int helper_{u}(int n) {{
            std::vector<int> v(static_cast<std::size_t>(n % 13 + 1), n);
            std::iota(v.begin(), v.end(), n);
            return std::accumulate(v.begin(), v.end(), 0);
        }}

        int use_{u}(int n) {{
            return {calls} + fast_{u % N_INLINE}(helper_{u}(n));
        }}

        std::string describe_{u}(int n) {{
            return "use_{u}=" + std::to_string(use_{u}(n));
        }}
        """)
    open(os.path.join(HERE, f"use_{u}.cpp"), "w").write(src)

main = ["// Generated by generate.py.", "#include <cstdio>", "#include <string>"]
main += [f"std::string describe_{u}(int n);" for u in range(N_USERS)]
main += ["int main(int argc, char**) {", "    int total = 0;"]
main += [f"    total += static_cast<int>(describe_{u}(argc + {u}).size());" for u in range(N_USERS)]
main += ['    std::printf("%d\\n", total);', "    return 0;", "}"]
open(os.path.join(HERE, "main.cpp"), "w").write("\n".join(main) + "\n")

cmake = textwrap.dedent(f"""\
    cmake_minimum_required(VERSION 3.28)
    project(cpp20_modules_bench CXX)
    set(CMAKE_CXX_STANDARD 20)
    set(CMAKE_CXX_EXTENSIONS OFF)
    add_library(mathlib)
    target_sources(mathlib PUBLIC FILE_SET CXX_MODULES FILES mathlib.cppm)
    add_executable(bench main.cpp {' '.join(f'use_{u}.cpp' for u in range(N_USERS))})
    target_link_libraries(bench mathlib)
    """)
open(os.path.join(HERE, "CMakeLists.txt"), "w").write(cmake)
print(f"wrote mathlib.cppm ({N_FUNCS} functions, {N_INLINE} inline), {N_USERS} importers, main.cpp, CMakeLists.txt")
